# Copyright 2021 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3.7'

volumes:
  mongo_data: {}
  neo4j_data: {}

networks:
  crawler_net:
    driver: bridge

services:
  mongo-db:
    image: library/mongo:bionic
    ports:
      - "27017:27017/tcp"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USR:-mongoUsr}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD:-mongoPwd}
    networks:
      - crawler_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo-db:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: on-failure

  crawler:
    image: "crawler-dev:latest"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://${MONGODB_USR:-mongoUsr}:${MONGODB_PWD:-mongoPwd}@mongo-db:27017
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mongo-db
    networks:
      - crawler_net
    restart: on-failure

  neo4j-db:
    image: neo4j:latest
    ports:
      - "7474:7474" # Neo4j web interface
      - "7687:7687" # Neo4j Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/11111111
    volumes:
      - neo4j_data:/data
    networks:
      - crawler_net